"""
Provides a Supabase client using environment variables and CRUD helper functions for the Note model.
"""

import os
from typing import Optional, List
from pydantic import BaseModel, Field
from dotenv import load_dotenv
from supabase import create_client, Client

# Always load environment variables from a .env file if present.
# This supports local development; production can provide env vars directly.
load_dotenv()

def get_supabase_client() -> Client:
    """
    Creates and returns an authenticated Supabase client,
    using SUPABASE_URL and SUPABASE_KEY from the environment.
    """
    supabase_url = os.getenv("SUPABASE_URL")
    supabase_key = os.getenv("SUPABASE_KEY")
    if not supabase_url or not supabase_key:
        raise RuntimeError(
            "Missing SUPABASE_URL or SUPABASE_KEY in environment. "
            "Set these variables or provide a .env file (see supabase.md/README)."
        )
    return create_client(supabase_url, supabase_key)

# PUBLIC_INTERFACE
class Note(BaseModel):
    """
    Represents a note object to be stored in Supabase.

    Fields:
        id: Unique identifier for the note (autogenerated).
        title: The title of the note.
        content: The main content of the note.
        created_at: Timestamp of note creation.
        updated_at: Timestamp of last update.
    """
    id: Optional[int] = Field(None, description="Unique identifier of the note")
    title: str = Field(..., description="Title of the note")
    content: str = Field(..., description="Note content")
    created_at: Optional[str] = Field(None, description="When the note was created (ISO format)")
    updated_at: Optional[str] = Field(None, description="When the note was last updated (ISO format)")

# PUBLIC_INTERFACE
def create_note(note: Note) -> Note:
    """
    Creates a note in Supabase and returns the created note.

    Args:
        note (Note): Note object without id/created_at/updated_at (these are set by Supabase).

    Returns:
        Note: Newly created note with all fields.
    """
    supabase = get_supabase_client()
    result = supabase.table("notes").insert(note.model_dump(exclude_unset=True)).execute()
    data = result.data[0]
    return Note(**data)

# PUBLIC_INTERFACE
def get_note(note_id: int) -> Optional[Note]:
    """
    Retrieves a note by its ID.

    Args:
        note_id (int): The note's unique identifier.

    Returns:
        Note or None if not found.
    """
    supabase = get_supabase_client()
    result = supabase.table("notes").select("*").eq("id", note_id).execute()
    data = result.data
    if not data:
        return None
    return Note(**data[0])

# PUBLIC_INTERFACE
def list_notes() -> List[Note]:
    """
    Returns all notes in the Supabase database.

    Returns:
        List[Note]: All notes currently stored.
    """
    supabase = get_supabase_client()
    result = supabase.table("notes").select("*").order("updated_at", desc=True).execute()
    notes = [Note(**item) for item in result.data]
    return notes

# PUBLIC_INTERFACE
def update_note(note_id: int, note: Note) -> Optional[Note]:
    """
    Updates an existing note.

    Args:
        note_id (int): The note's unique identifier.
        note (Note): New values for the note.

    Returns:
        Note or None if not found.
    """
    supabase = get_supabase_client()
    result = supabase.table("notes").update(note.model_dump(exclude_unset=True)).eq("id", note_id).execute()
    data = result.data
    if not data:
        return None
    return Note(**data[0])

# PUBLIC_INTERFACE
def delete_note(note_id: int) -> bool:
    """
    Deletes a note by ID.

    Args:
        note_id (int): The note's unique identifier.

    Returns:
        bool: True if the note was deleted, False otherwise.
    """
    supabase = get_supabase_client()
    result = supabase.table("notes").delete().eq("id", note_id).execute()
    return bool(result.data and len(result.data) > 0)
